language: java
sudo: true
dist: trusty
jdk: oraclejdk8

before_install:
  - chmod +x mvnw
  
build:
    - script: mvn clean package -DskipTests
    

deploy:
  provider: heroku
  api_key: $API_KEY_HEROKU
  app: plateformecours