language: java

before_install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

build:
    - script: mvn clean package -DskipTests
    

deploy:
  provider: heroku
  api_key: $API_KEY_HEROKU
  app: plateformecours